// 人生抉择 / 事件数据库（gacha 抽卡池）。
// 从 page.tsx 抽离，便于规模化扩充到数百个事件而不污染主组件。
//
// 设计约定（与引擎一致）：
//  - 每个选择都有"代价"(cost)与"收益"(gain)：代价从选择当年起生效，收益在 delayYears 年后兑现。
//  - 心情(mood)是隐藏分——只画成多巴胺曲线，不直接显示数字；过低会中途离世。
//  - worthy=true 表示"性价比高/社会称许"的选择；trash=true 表示 gain<cost 的垃圾选项。
//  - requires：前置事件，必须已选中这些 id，本卡才会进入抽卡池（链式剧情）。
//  - unlocks：后置事件，选中本卡后才会解锁的事件 id（用于链式提示）。

export type LifeDebuff = {
  wealthMul: number // 资产乘子（< 1 表示缩水）
  bodyDelta: number // 身体机能加成（多为负）
  eduDelta: number // 学历加成（荒废为负）
  identityDelta: number // 社会身份加成（多为负）
  moodDelta: number // 心情/多巴胺直给（隐藏分，正=爽，负=苦）
}

export const NO_DEBUFF: LifeDebuff = { wealthMul: 1, bodyDelta: 0, eduDelta: 0, identityDelta: 0, moodDelta: 0 }

export type ChoiceTrack = 'love' | 'career'

export type LifeChoice = {
  id: string
  emoji: string
  name: string
  track: ChoiceTrack
  ageStart: number
  ageEnd: number
  delayYears: number // 收益在选择后多少年兑现
  worthy: boolean // 性价比高 / 社会称许（true）；人性化 / 垃圾选项（false）
  trash?: boolean // 明确的垃圾选项（gain < cost，纯爽一时）
  event?: boolean // 人生事件（亲属离世 / 生育等），并非纯主动决策
  cost: Partial<LifeDebuff> // 选择当年起生效的代价
  gain: Partial<LifeDebuff> // delayYears 年后兑现的收益
  desc: string
  consequence: string // 后果文案（带黑色幽默）
  requires?: string[] // 前置事件：必须已选中这些 id，本卡才会进入抽卡池
  unlocks?: string[] // 后置事件：选中本卡后才会解锁的事件 id（用于链式提示）
  extra?: Record<string, number | string | boolean> // 扩展字段（稀有度 / 标签 / 自定义参数等）
}

export const LIFE_CHOICES: LifeChoice[] = [
  // ——————— 事业线 · 性价比高的正经选择 ———————
  {
    id: 'study_hard', emoji: '📚', name: '勤学苦读', track: 'career',
    ageStart: 12, ageEnd: 18, delayYears: 6, worthy: true,
    cost: { moodDelta: -6, bodyDelta: -3 },
    gain: { eduDelta: 18, identityDelta: 6, moodDelta: 4 },
    desc: '把青春押在课本上，目标一所好大学。',
    consequence: '寒窗数载终上岸：学历地基扎实，但也错过了不少疯玩的少年时光。',
  },
  {
    id: 'top_university', emoji: '🎓', name: '冲刺名校', track: 'career',
    ageStart: 17, ageEnd: 20, delayYears: 4, worthy: true,
    cost: { moodDelta: -10, wealthMul: 0.9 },
    gain: { eduDelta: 14, identityDelta: 12, wealthMul: 1.3, moodDelta: 5 },
    unlocks: ['study_abroad', 'grad_school'],
    desc: '冲刺 985 / Top 名校，赌一个更高的人生起点。',
    consequence: '名校光环加身：人脉与平台跃升，代价是高压几年与社交荒漠。',
  },
  {
    id: 'grad_school', emoji: '🔬', name: '读研深造', track: 'career',
    ageStart: 22, ageEnd: 27, delayYears: 4, worthy: true,
    cost: { wealthMul: 0.7, moodDelta: -6 },
    gain: { eduDelta: 12, identityDelta: 8, wealthMul: 1.7, moodDelta: 8 },
    desc: '继续深造，攒下更高的学历与研究资本。',
    consequence: '延迟入场换来更高天花板；同龄人已工作攒钱，你还在实验室搬砖。',
  },
  {
    id: 'civil_service', emoji: '🏛️', name: '考公上岸', track: 'career',
    ageStart: 22, ageEnd: 30, delayYears: 3, worthy: true,
    cost: { moodDelta: -8 },
    gain: { identityDelta: 14, wealthMul: 1.1, moodDelta: 6 },
    desc: '千军万马过独木桥，求一份稳定与体面。',
    consequence: '宇宙的尽头是编制：稳定、体面、旱涝保收，激情也随之归于平淡。',
  },
  {
    id: 'startup', emoji: '🚀', name: '下海创业', track: 'career',
    ageStart: 25, ageEnd: 42, delayYears: 5, worthy: true,
    cost: { wealthMul: 0.5, bodyDelta: -8, moodDelta: -10 },
    gain: { wealthMul: 2.4, identityDelta: 12, moodDelta: 10 },
    desc: '梭哈一把，赌自己能成为下一个传奇。',
    consequence: '九死一生：熬过来财富与身份双跃迁，熬不过来就是中年返贫。',
  },
  {
    id: 'job_hop', emoji: '🪜', name: '跳槽涨薪', track: 'career',
    ageStart: 26, ageEnd: 45, delayYears: 1, worthy: true,
    cost: { moodDelta: -4 },
    gain: { wealthMul: 1.4, identityDelta: 4 },
    desc: '此处不留爷，自有留爷处——用脚投票涨薪。',
    consequence: '薪资曲线陡升；代价是简历好看但少了点"老员工"的归属感。',
  },
  {
    id: 'invest', emoji: '📈', name: '理财投资', track: 'career',
    ageStart: 25, ageEnd: 60, delayYears: 5, worthy: true,
    cost: { wealthMul: 0.9, moodDelta: -2 },
    gain: { wealthMul: 1.6, moodDelta: 3 },
    desc: '让钱生钱，定投指数 + 资产配置躺赢。',
    consequence: '复利的雪球滚起来；前提是你扛住了中途的几次大回撤。',
  },
  {
    id: 'buy_house', emoji: '🏠', name: '上车买房', track: 'career',
    ageStart: 28, ageEnd: 42, delayYears: 0, worthy: true,
    cost: { wealthMul: 0.6, moodDelta: -6 },
    gain: { identityDelta: 8, moodDelta: 7 },
    desc: '掏空六个钱包，换一张城市的入场券。',
    consequence: '终于有了自己的窝与安全感；同时背上三十年房贷，从此不敢裸辞。',
  },
  {
    id: 'fitness', emoji: '🏃', name: '坚持健身', track: 'career',
    ageStart: 18, ageEnd: 65, delayYears: 3, worthy: true,
    cost: { moodDelta: -3 },
    gain: { bodyDelta: 16, moodDelta: 8 },
    desc: '自律给我自由：撸铁、跑步、规律作息。',
    consequence: '身体是革命的本钱：体能与心情双丰收，慢病时间表整体后移。',
  },
  // ——————— 事业线 · 垃圾选项（gain < cost，爽一时） ———————
  {
    id: 'gaming', emoji: '🎮', name: '游戏人生', track: 'career',
    ageStart: 13, ageEnd: 60, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.5, eduDelta: -18, bodyDelta: -8, identityDelta: -8 },
    gain: { moodDelta: 9 },
    desc: '沉迷游戏，立志冲上国服第一。',
    consequence: '段位封神：最强王者·国服前 100（并无卵用）；学业事业双双荒废。',
  },
  {
    id: 'idle', emoji: '🛋️', name: '无所事事', track: 'career',
    ageStart: 18, ageEnd: 60, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.5, eduDelta: -14, identityDelta: -12 },
    gain: { moodDelta: 4 },
    desc: '一天天躺着刷手机，时间在指缝里溜走。',
    consequence: '技能荒废、简历空窗、资产缩水，HR 已读不回。',
  },
  {
    id: 'travel', emoji: '🌍', name: '环球旅行', track: 'career',
    ageStart: 22, ageEnd: 55, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.4, identityDelta: -4 },
    gain: { moodDelta: 13, eduDelta: 3 },
    desc: '说走就走，背包环游世界两三年。',
    consequence: '见识 +++、存款 ---、简历出现大段空窗，回国后从零开始。',
  },
  {
    id: 'gap', emoji: '🏝️', name: 'Gap 一阵子', track: 'career',
    ageStart: 22, ageEnd: 55, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.7, identityDelta: -6 },
    gain: { moodDelta: 7 },
    desc: '裸辞 gap，去寻找诗和远方与自己。',
    consequence: '短期巨爽，长期错过晋升窗口与复利，回归赛道时已被后浪拍在沙滩。',
  },
  {
    id: 'lieflat', emoji: '😪', name: '躺平摆烂', track: 'career',
    ageStart: 22, ageEnd: 70, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.55, bodyDelta: -5, identityDelta: -8 },
    gain: { moodDelta: 6 },
    desc: '不卷了，开启最低欲望生存模式。',
    consequence: '压力 --，但收入封顶、身材走样、社会存在感稀薄。',
  },
  {
    id: 'gacha', emoji: '💸', name: '氪金抽卡', track: 'career',
    ageStart: 16, ageEnd: 60, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.5 },
    gain: { moodDelta: 8 },
    desc: '为爱发电，月月 648，仓库全满级。',
    consequence: '账号金光闪闪、钱包空空如也；版本更新后角色一夜归零。',
  },
  {
    id: 'mahjong', emoji: '🀄', name: '打麻将', track: 'career',
    ageStart: 25, ageEnd: 80, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.8, bodyDelta: -4, identityDelta: -3 },
    gain: { moodDelta: 7 },
    desc: '三缺一就是你，雀神附体杀四方。',
    consequence: '牌桌一坐一整天：手气好赢顿火锅，手气差输掉半月工资，腰肌劳损附赠。',
  },
  // ——————— 感情线 · 人性化 / 性价比高的选择 ———————
  {
    id: 'first_love', emoji: '💕', name: '认真初恋', track: 'love',
    ageStart: 16, ageEnd: 24, delayYears: 1, worthy: false,
    cost: { moodDelta: -3 },
    gain: { moodDelta: 12, identityDelta: 2 },
    desc: '懵懂青涩的第一段长期亲密关系。',
    consequence: '心动、争吵、和好、再心动——这段记忆会暖一辈子，哪怕最后没在一起。',
  },
  {
    id: 'date', emoji: '💘', name: '搞对象谈恋爱', track: 'love',
    ageStart: 18, ageEnd: 38, delayYears: 0, worthy: false,
    cost: { wealthMul: 0.9, moodDelta: -2 },
    gain: { moodDelta: 9 },
    unlocks: ['propose', 'long_distance'],
    desc: '约会、看电影、互送礼物，谈一场恋爱。',
    consequence: '甜蜜暴击钱包：纪念日、节日、惊喜一个不落，幸福感拉满。',
  },
  {
    id: 'marriage', emoji: '💍', name: '步入婚姻', track: 'love',
    ageStart: 26, ageEnd: 42, delayYears: 1, worthy: true,
    cost: { wealthMul: 0.7, moodDelta: -5 },
    gain: { moodDelta: 10, identityDelta: 8, bodyDelta: 2 },
    unlocks: ['divorce', 'affair'],
    desc: '领证、办婚礼，从此人生有了搭子。',
    consequence: '从单身贵族到柴米油盐：彩礼婚房掏空积蓄，但多了个并肩扛事的人。',
  },
  {
    id: 'have_child', emoji: '👶', name: '生育小孩', track: 'love',
    ageStart: 26, ageEnd: 44, delayYears: 2, worthy: true, event: true,
    cost: { wealthMul: 0.6, bodyDelta: -6, moodDelta: -8 },
    gain: { moodDelta: 16, identityDelta: 6 },
    unlocks: ['second_child'],
    desc: '迎接一个新生命，升级为爸 / 妈。',
    consequence: '吞金兽降临：睡眠和存款双双告急，但他第一声"爸/妈"能让你瞬间回血。',
  },
  {
    id: 'maintain_love', emoji: '🤝', name: '经营婚姻', track: 'love',
    ageStart: 30, ageEnd: 65, delayYears: 2, worthy: true,
    cost: { moodDelta: -4 },
    gain: { moodDelta: 9 },
    desc: '定期约会、好好沟通，对抗七年之痒。',
    consequence: '婚姻是需要浇水的花：用心经营换来细水长流，疏于打理则同床异梦。',
  },
  {
    id: 'good_friends', emoji: '🍻', name: '维系挚友', track: 'love',
    ageStart: 18, ageEnd: 75, delayYears: 1, worthy: false,
    cost: { wealthMul: 0.95, moodDelta: -1 },
    gain: { moodDelta: 7 },
    desc: '三五好友，时常聚聚，有事互相搭把手。',
    consequence: '成年人最奢侈的，是几个能深夜接电话的朋友——这笔情感存款利息很高。',
  },
  // ——————— 感情线 · 垃圾选项 / 沉重事件 ———————
  {
    id: 'toxic_love', emoji: '💔', name: '沉溺烂桃花', track: 'love',
    ageStart: 22, ageEnd: 45, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.8, moodDelta: -6, identityDelta: -4 },
    gain: { moodDelta: 5 },
    desc: '明知是错的人，却一次次飞蛾扑火。',
    consequence: '在烂关系里反复内耗：青春、钱财、信任一起赔光，朋友都劝不动。',
  },
  {
    id: 'brawl', emoji: '🥊', name: '斗殴霸凌', track: 'love',
    ageStart: 13, ageEnd: 28, delayYears: 0, worthy: false, trash: true,
    cost: { identityDelta: -14, eduDelta: -6, wealthMul: 0.85 },
    gain: { moodDelta: 6, bodyDelta: 2 },
    desc: '校园 / 街头逞凶斗狠，称王称霸。',
    consequence: '一时威风八面，留下案底与仇家：升学就业处处碰壁，赔款道歉是家常便饭。',
  },
  {
    id: 'relative_death', emoji: '⚰️', name: '至亲离世', track: 'love',
    ageStart: 35, ageEnd: 85, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -16, bodyDelta: -2 },
    gain: { identityDelta: 2 },
    desc: '经历父母 / 至亲的离去（人生必修的一课）。',
    consequence: '子欲养而亲不待：巨大的情绪冲击，让人一夜长大，也更懂得珍惜眼前人。',
  },
  // ——————— 新增 · 少年成长链（可与"勤学苦读"组合，部分有前置） ———————
  {
    id: 'read_books', emoji: '📖', name: '博览群书', track: 'career',
    ageStart: 6, ageEnd: 16, delayYears: 4, worthy: true,
    cost: { moodDelta: -2 },
    gain: { eduDelta: 8, identityDelta: 2, moodDelta: 3 },
    unlocks: ['science_olympiad'],
    desc: '泡在书海里，课外阅读量惊人。',
    consequence: '上知天文下知地理：谈吐自带书卷气，作文素材信手拈来。',
  },
  {
    id: 'learn_instrument', emoji: '🎻', name: '学门乐器', track: 'career',
    ageStart: 6, ageEnd: 16, delayYears: 5, worthy: true,
    cost: { wealthMul: 0.95, moodDelta: -3 },
    gain: { identityDelta: 7, moodDelta: 5 },
    unlocks: ['art_exam'],
    desc: '钢琴 / 小提琴 / 吉他，考级路上不回头。',
    consequence: '十级证书到手：多了一项体面才艺，也搭进去无数个练琴的周末。',
  },
  {
    id: 'sports_team', emoji: '⚽', name: '校队主力', track: 'career',
    ageStart: 10, ageEnd: 19, delayYears: 3, worthy: true,
    cost: { moodDelta: -2, eduDelta: -2 },
    gain: { bodyDelta: 12, identityDelta: 5, moodDelta: 4 },
    desc: '校运动队主力，挥洒汗水与荷尔蒙。',
    consequence: '身体素质拉满、校园人气爆棚；偶尔为集训耽误功课。',
  },
  {
    id: 'puppy_love', emoji: '💞', name: '懵懂早恋', track: 'love',
    ageStart: 13, ageEnd: 18, delayYears: 0, worthy: false, trash: true,
    cost: { eduDelta: -5, moodDelta: -2 },
    gain: { moodDelta: 9 },
    desc: '课桌传纸条，放学一起走的青涩心动。',
    consequence: '甜过初恋糖：成绩可能滑坡，但那份心跳多年后仍记得。',
  },
  {
    id: 'science_olympiad', emoji: '🏅', name: '学科竞赛', track: 'career',
    ageStart: 14, ageEnd: 19, delayYears: 3, worthy: true,
    cost: { moodDelta: -6, bodyDelta: -2 },
    gain: { eduDelta: 14, identityDelta: 10, moodDelta: 4 },
    requires: ['read_books'],
    desc: '搏一个省一 / 国奖，叩开保送的大门。',
    consequence: '竞赛党的荣耀：一战封神直通名校，或陪跑三年只剩黑眼圈。',
  },
  {
    id: 'art_exam', emoji: '🎨', name: '艺考特长', track: 'career',
    ageStart: 15, ageEnd: 20, delayYears: 2, worthy: false,
    cost: { wealthMul: 0.8, moodDelta: -5 },
    gain: { identityDelta: 8, eduDelta: 4, moodDelta: 6 },
    requires: ['learn_instrument'],
    desc: '走艺术 / 体育特长生路线，另辟蹊径。',
    consequence: '艺考独木桥：文化课压力小一些，集训烧钱、前途看天赋与运气。',
  },
  // ——————— 新增 · 升学深造分支（名校解锁） ———————
  {
    id: 'study_abroad', emoji: '✈️', name: '出国留学', track: 'career',
    ageStart: 18, ageEnd: 28, delayYears: 4, worthy: true,
    cost: { wealthMul: 0.45, moodDelta: -6 },
    gain: { eduDelta: 14, identityDelta: 12, wealthMul: 1.4, moodDelta: 5 },
    requires: ['top_university'],
    desc: '名校加持下冲刺海外深造，开眼看世界。',
    consequence: '镀金归来：视野与履历升级，也烧掉一套房 + 几年异乡孤独。',
  },
  // ——————— 新增 · 职场进阶链 ———————
  {
    id: 'overtime_996', emoji: '🌃', name: '996 拼搏', track: 'career',
    ageStart: 23, ageEnd: 40, delayYears: 2, worthy: true,
    cost: { bodyDelta: -8, moodDelta: -8 },
    gain: { wealthMul: 1.5, identityDelta: 4, moodDelta: 2 },
    unlocks: ['promotion'],
    desc: '大厂高强度内卷，用健康换期权。',
    consequence: '钱包鼓了、发际线高了：年终奖到账的快乐，体检报告的眼泪。',
  },
  {
    id: 'side_hustle', emoji: '🧰', name: '副业搞钱', track: 'career',
    ageStart: 24, ageEnd: 52, delayYears: 2, worthy: true,
    cost: { moodDelta: -4, bodyDelta: -3 },
    gain: { wealthMul: 1.3, moodDelta: 3 },
    desc: '下班接单 / 摆摊 / 自媒体，开辟第二曲线。',
    consequence: '睡后收入初体验：多一份底气，也少了不少躺平摸鱼的时光。',
  },
  {
    id: 'promotion', emoji: '📊', name: '升职管理', track: 'career',
    ageStart: 30, ageEnd: 52, delayYears: 2, worthy: true,
    cost: { moodDelta: -5 },
    gain: { identityDelta: 10, wealthMul: 1.4, moodDelta: 4 },
    requires: ['overtime_996'],
    desc: '熬出头当上管理层，手里有了兵权。',
    consequence: '从打工人到带团队：话语权与薪资双升，背锅与开会也翻倍。',
  },
  {
    id: 'buy_car', emoji: '🚗', name: '买车代步', track: 'career',
    ageStart: 24, ageEnd: 50, delayYears: 0, worthy: false,
    cost: { wealthMul: 0.85, moodDelta: -1 },
    gain: { moodDelta: 6, identityDelta: 3 },
    desc: '提一辆车，从此告别挤地铁。',
    consequence: '有车一族真香：通勤体面、周末能远行；油费保养停车费随之而来。',
  },
  {
    id: 'health_checkup', emoji: '🩺', name: '定期体检', track: 'career',
    ageStart: 30, ageEnd: 75, delayYears: 1, worthy: true,
    cost: { wealthMul: 0.97 },
    gain: { bodyDelta: 6, moodDelta: 2 },
    desc: '每年一次全身体检，早发现早安心。',
    consequence: '把慢病掐灭在萌芽：花小钱买安心，体检前夜照样焦虑。',
  },
  {
    id: 'crypto_yolo', emoji: '🪙', name: '梭哈币圈', track: 'career',
    ageStart: 20, ageEnd: 55, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.35, moodDelta: -2 },
    gain: { moodDelta: 9 },
    desc: '全仓杠杆冲山寨币，赌一夜暴富。',
    consequence: '凌晨盯盘心跳过山车：要么财富自由，要么归零吃面，多数是后者。',
  },
  // ——————— 新增 · 感情进阶链（多为前置解锁） ———————
  {
    id: 'pet', emoji: '🐶', name: '养只宠物', track: 'love',
    ageStart: 20, ageEnd: 65, delayYears: 1, worthy: false,
    cost: { wealthMul: 0.95, moodDelta: -1 },
    gain: { moodDelta: 8 },
    desc: '领养一只猫 / 狗，从此家里有了毛孩子。',
    consequence: '吸猫遛狗治愈一切：孤独感大降，铲屎与看病账单悄悄上涨。',
  },
  {
    id: 'blind_date', emoji: '🌹', name: '相亲脱单', track: 'love',
    ageStart: 25, ageEnd: 42, delayYears: 1, worthy: false,
    cost: { wealthMul: 0.95, moodDelta: -2 },
    gain: { moodDelta: 6, identityDelta: 1 },
    desc: '父母安排，咖啡厅里高效配对。',
    consequence: '相亲市场明码标价：条件匹配则速通领证，话不投机则尬聊两小时。',
  },
  {
    id: 'long_distance', emoji: '📞', name: '异地恋', track: 'love',
    ageStart: 20, ageEnd: 36, delayYears: 0, worthy: false,
    cost: { moodDelta: -6, wealthMul: 0.92 },
    gain: { moodDelta: 6 },
    requires: ['date'],
    desc: '隔着几百公里靠视频续命的爱情。',
    consequence: '机票与思念齐飞：熬过来感情更牢，熬不过就败给了距离。',
  },
  {
    id: 'propose', emoji: '💐', name: '浪漫求婚', track: 'love',
    ageStart: 24, ageEnd: 40, delayYears: 0, worthy: true,
    cost: { wealthMul: 0.9, moodDelta: -2 },
    gain: { moodDelta: 11, identityDelta: 3 },
    requires: ['date'],
    desc: '精心策划一场单膝跪地的惊喜。',
    consequence: '钻戒与玫瑰齐飞：朋友圈点赞拉满，钱包也跟着失血。',
  },
  {
    id: 'second_child', emoji: '👨‍👩‍👧‍👦', name: '生育二胎', track: 'love',
    ageStart: 28, ageEnd: 45, delayYears: 2, worthy: true, event: true,
    cost: { wealthMul: 0.6, bodyDelta: -5, moodDelta: -8 },
    gain: { moodDelta: 12, identityDelta: 4 },
    requires: ['have_child'],
    desc: '响应号召，再添一个小神兽。',
    consequence: '二胎家庭欢乐加倍、开销也加倍：学区房与奶粉钱让钱包雪上加霜。',
  },
  {
    id: 'affair', emoji: '🙈', name: '婚内出轨', track: 'love',
    ageStart: 28, ageEnd: 58, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.7, moodDelta: -4, identityDelta: -12 },
    gain: { moodDelta: 6 },
    requires: ['marriage'],
    unlocks: ['divorce'],
    desc: '抵不住诱惑，在婚姻外越了界。',
    consequence: '纸终究包不住火：道德与法律双重反噬，家庭与名声一地鸡毛。',
  },
  {
    id: 'divorce', emoji: '🪦', name: '协议离婚', track: 'love',
    ageStart: 29, ageEnd: 60, delayYears: 0, worthy: false, event: true,
    cost: { wealthMul: 0.6, moodDelta: -12, identityDelta: -4 },
    gain: { moodDelta: 5 },
    requires: ['marriage'],
    desc: '一别两宽，分割财产各自安好。',
    consequence: '围城散场：财产砍半、情绪重创，但也重获自由与喘息。',
  },
  {
    id: 'volunteer', emoji: '🤲', name: '公益志愿', track: 'love',
    ageStart: 18, ageEnd: 75, delayYears: 1, worthy: false,
    cost: { wealthMul: 0.97, moodDelta: -1 },
    gain: { moodDelta: 7, identityDelta: 3 },
    desc: '支教 / 助老 / 救灾，做点纯粹利他的事。',
    consequence: '被需要的感觉很上头：物质没增加，精神却异常富足。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 婴幼儿 & 学前（0–6 岁）：早期养育与启蒙，奠定四维地基
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'breastfed', emoji: '🍼', name: '母乳喂养', track: 'love',
    ageStart: 0, ageEnd: 2, delayYears: 1, worthy: true, event: true,
    cost: { moodDelta: -1 },
    gain: { bodyDelta: 6, moodDelta: 4 },
    desc: '妈妈坚持亲喂，攒下人生第一波免疫力。',
    consequence: '抵抗力打底：少生病、亲子依恋更牢，这份安全感能管很多年。',
  },
  {
    id: 'early_edu', emoji: '🧩', name: '早教启蒙', track: 'career',
    ageStart: 2, ageEnd: 5, delayYears: 4, worthy: false,
    cost: { wealthMul: 0.92, moodDelta: -2 },
    gain: { eduDelta: 5, identityDelta: 2, moodDelta: 1 },
    desc: '蒙氏 / 早教班 / 闪卡，赢在起跑线。',
    consequence: '认知抢跑一小步：花了不少钱，效果因人而异，至少识字早了点。',
  },
  {
    id: 'left_behind', emoji: '🏚️', name: '留守儿童', track: 'love',
    ageStart: 3, ageEnd: 12, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -10, identityDelta: -3 },
    gain: { bodyDelta: 2 },
    desc: '父母外出打工，由爷爷奶奶带大。',
    consequence: '一年见父母一两面：独立得早，情感的缺口却要花半生去填补。',
  },
  {
    id: 'kindergarten_star', emoji: '⭐', name: '幼儿园之星', track: 'love',
    ageStart: 3, ageEnd: 6, delayYears: 1, worthy: false,
    cost: {},
    gain: { moodDelta: 6, identityDelta: 3 },
    desc: '上台表演、当小班长，自信心爆棚。',
    consequence: '从小就是焦点：表达欲与镜头感拉满，老师家长一片夸。',
  },
  {
    id: 'picky_eater', emoji: '🥦', name: '挑食偏食', track: 'love',
    ageStart: 3, ageEnd: 10, delayYears: 2, worthy: false, trash: true,
    cost: { bodyDelta: -5 },
    gain: { moodDelta: 3 },
    desc: '只吃肉不吃菜，把饭桌变成拉锯战。',
    consequence: '营养不均衡：个子和体质都吃了点亏，长大后才追悔。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 小学（6–12 岁）：兴趣、习惯、第一次社会化
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'class_monitor', emoji: '🎖️', name: '当班长', track: 'career',
    ageStart: 7, ageEnd: 12, delayYears: 4, worthy: true,
    cost: { moodDelta: -2 },
    gain: { identityDelta: 6, moodDelta: 3 },
    unlocks: ['student_council'],
    desc: '老师钦点的班长，管纪律收作业。',
    consequence: '从小练领导力：责任心与人缘双修，偶尔也被同学背后嫌弃。',
  },
  {
    id: 'painting_class', emoji: '🖌️', name: '学画画', track: 'career',
    ageStart: 5, ageEnd: 14, delayYears: 5, worthy: false,
    cost: { wealthMul: 0.96, moodDelta: -1 },
    gain: { identityDelta: 4, moodDelta: 4 },
    unlocks: ['art_exam'],
    desc: '素描水彩国画轮番上，周末泡画室。',
    consequence: '审美在线、手也巧：多一门表达方式，将来朋友圈配图不求人。',
  },
  {
    id: 'go_chess', emoji: '⚫', name: '学围棋', track: 'career',
    ageStart: 5, ageEnd: 14, delayYears: 5, worthy: true,
    cost: { moodDelta: -2 },
    gain: { eduDelta: 5, identityDelta: 3, moodDelta: 2 },
    desc: '黑白棋盘上修炼计算力与大局观。',
    consequence: '棋盘如人生：定段证书在手，专注力与逻辑悄悄上了个台阶。',
  },
  {
    id: 'swimming', emoji: '🏊', name: '学游泳', track: 'career',
    ageStart: 5, ageEnd: 16, delayYears: 3, worthy: true,
    cost: { moodDelta: -1 },
    gain: { bodyDelta: 8, moodDelta: 3 },
    desc: '解锁一项保命技能，顺便强身健体。',
    consequence: '水里来去自如：体质增强，关键时刻还能救人一命。',
  },
  {
    id: 'bully_others', emoji: '😈', name: '欺凌同学', track: 'love',
    ageStart: 8, ageEnd: 17, delayYears: 3, worthy: false, trash: true,
    cost: { identityDelta: -10, moodDelta: -3 },
    gain: { moodDelta: 5 },
    unlocks: ['expelled'],
    desc: '在校园里当"老大"，欺负弱小取乐。',
    consequence: '一时作威作福：被处分、被记过、被家长找上门，人品标签贴一辈子。',
  },
  {
    id: 'bullied', emoji: '🥀', name: '遭受霸凌', track: 'love',
    ageStart: 8, ageEnd: 17, delayYears: 2, worthy: false, event: true,
    cost: { moodDelta: -14, identityDelta: -4, bodyDelta: -2 },
    gain: { identityDelta: 2 },
    unlocks: ['fight_back', 'see_counselor'],
    desc: '成为被孤立、被欺负的那个人。',
    consequence: '黑暗的一段日子：自尊被反复碾压，留下的心理阴影需要很久才能愈合。',
  },
  {
    id: 'fight_back', emoji: '✊', name: '奋起反抗', track: 'love',
    ageStart: 9, ageEnd: 18, delayYears: 1, worthy: true,
    cost: { bodyDelta: -3, moodDelta: -2 },
    gain: { identityDelta: 8, moodDelta: 8 },
    requires: ['bullied'],
    desc: '不再忍气吞声，正面硬刚施暴者。',
    consequence: '把尊严夺回来：可能挂彩，但从此再没人敢小看你，内心也长出了铠甲。',
  },
  {
    id: 'see_counselor', emoji: '🧑‍⚕️', name: '寻求心理疏导', track: 'love',
    ageStart: 9, ageEnd: 70, delayYears: 1, worthy: true,
    cost: { wealthMul: 0.97 },
    gain: { moodDelta: 9, bodyDelta: 1 },
    desc: '找心理老师 / 咨询师，把情绪说出来。',
    consequence: '求助不是软弱：被看见、被接住之后，那些结慢慢解开了。',
  },
  {
    id: 'expelled', emoji: '🚫', name: '被劝退记过', track: 'career',
    ageStart: 13, ageEnd: 18, delayYears: 0, worthy: false, event: true,
    cost: { eduDelta: -12, identityDelta: -10, moodDelta: -6 },
    gain: { moodDelta: 2 },
    requires: ['bully_others'],
    desc: '闯祸太多，吃了处分甚至被劝退。',
    consequence: '档案上一道疤：升学路被堵死大半，得花数倍努力才能洗白。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 中考备战（13–16 岁）：分流的第一道关
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'zhongkao_grind', emoji: '📝', name: '备战中考', track: 'career',
    ageStart: 13, ageEnd: 16, delayYears: 2, worthy: true,
    cost: { moodDelta: -8, bodyDelta: -3 },
    gain: { eduDelta: 12, identityDelta: 4, moodDelta: 3 },
    unlocks: ['key_highschool', 'vocational_school'],
    desc: '初三冲刺，刷题刷到深夜。',
    consequence: '人生第一道分水岭：一分一操场，这一搏直接决定去普高还是职高。',
  },
  {
    id: 'key_highschool', emoji: '🏫', name: '考上重点高中', track: 'career',
    ageStart: 15, ageEnd: 16, delayYears: 3, worthy: true,
    cost: { moodDelta: -4 },
    gain: { eduDelta: 10, identityDelta: 8, moodDelta: 5 },
    requires: ['zhongkao_grind'],
    unlocks: ['gaokao_grind'],
    desc: '挤进本地最好的高中，赢得名校预备席。',
    consequence: '站上更高的平台：身边全是卷王，压力山大但上限也更高。',
  },
  {
    id: 'vocational_school', emoji: '🔧', name: '读职高技校', track: 'career',
    ageStart: 15, ageEnd: 18, delayYears: 3, worthy: false,
    cost: { identityDelta: -4, moodDelta: -2 },
    gain: { eduDelta: 4, bodyDelta: 2, moodDelta: 3 },
    unlocks: ['learn_trade'],
    desc: '中考失利，转读职业学校学一技之长。',
    consequence: '换条赛道：升学光环少了，但一门手艺傍身，照样能闯出路。',
  },
  {
    id: 'learn_trade', emoji: '🛠️', name: '学门手艺', track: 'career',
    ageStart: 16, ageEnd: 40, delayYears: 3, worthy: true,
    cost: { bodyDelta: -3, moodDelta: -2 },
    gain: { wealthMul: 1.25, identityDelta: 3, moodDelta: 4 },
    requires: ['vocational_school'],
    desc: '汽修 / 厨艺 / 编程 / 电工，把技能练到精。',
    consequence: '一技在手吃喝不愁：蓝领里的高薪，靠手艺活得踏实。',
  },
  {
    id: 'rebel_phase', emoji: '🤬', name: '叛逆期', track: 'love',
    ageStart: 13, ageEnd: 18, delayYears: 1, worthy: false, trash: true,
    cost: { eduDelta: -6, moodDelta: -4, identityDelta: -3 },
    gain: { moodDelta: 6 },
    desc: '跟父母老师对着干，离家出走、染发逃课。',
    consequence: '青春期火山喷发：和家里冷战大半年，成绩与亲情一起滑坡。',
  },
  {
    id: 'crush_secret', emoji: '🌸', name: '暗恋同桌', track: 'love',
    ageStart: 13, ageEnd: 19, delayYears: 0, worthy: false,
    cost: { moodDelta: -2 },
    gain: { moodDelta: 7 },
    desc: '把心事藏在课本里，偷看 ta 的背影。',
    consequence: '青涩又美好：没说出口的喜欢，成了多年后嘴角的一抹微笑。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 高考备战（16–19 岁）：千军万马过独木桥
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'gaokao_grind', emoji: '✍️', name: '备战高考', track: 'career',
    ageStart: 16, ageEnd: 19, delayYears: 2, worthy: true,
    cost: { moodDelta: -12, bodyDelta: -5 },
    gain: { eduDelta: 16, identityDelta: 6, moodDelta: 4 },
    unlocks: ['gaokao_win', 'gaokao_fail', 'hardcore_study'],
    desc: '高三炼狱，五年高考三年模拟堆成山。',
    consequence: '黑色高三：睡眠以分钟计，所有筹码押在六月那两天。',
  },
  {
    id: 'hardcore_study', emoji: '🏭', name: '衡水式刷题', track: 'career',
    ageStart: 16, ageEnd: 19, delayYears: 2, worthy: false,
    cost: { moodDelta: -10, bodyDelta: -6 },
    gain: { eduDelta: 14, moodDelta: 1 },
    requires: ['gaokao_grind'],
    desc: '军事化管理，把自己变成做题机器。',
    consequence: '分数确实上去了：代价是被掏空的兴趣与近视加深的双眼。',
  },
  {
    id: 'gaokao_win', emoji: '🎉', name: '高考超常发挥', track: 'career',
    ageStart: 18, ageEnd: 19, delayYears: 4, worthy: true,
    cost: { moodDelta: -2 },
    gain: { eduDelta: 12, identityDelta: 12, wealthMul: 1.2, moodDelta: 10 },
    requires: ['gaokao_grind'],
    unlocks: ['top_university'],
    desc: '考场如有神助，分数比平时高出一截。',
    consequence: '一战封神：录取通知书来自梦校，全家奔走相告，人生开了局好牌。',
  },
  {
    id: 'gaokao_fail', emoji: '💧', name: '高考失利', track: 'career',
    ageStart: 18, ageEnd: 19, delayYears: 1, worthy: false, event: true,
    cost: { eduDelta: -4, identityDelta: -6, moodDelta: -12 },
    gain: { moodDelta: 2 },
    requires: ['gaokao_grind'],
    unlocks: ['repeat_year'],
    desc: '发挥失常，分数滑档去了不理想的学校。',
    consequence: '一考失意：与梦校擦肩而过，是认命还是复读，又是一道难题。',
  },
  {
    id: 'repeat_year', emoji: '🔁', name: '复读一年', track: 'career',
    ageStart: 18, ageEnd: 20, delayYears: 2, worthy: true,
    cost: { moodDelta: -10, bodyDelta: -3, wealthMul: 0.95 },
    gain: { eduDelta: 10, identityDelta: 6, moodDelta: 6 },
    requires: ['gaokao_fail'],
    desc: '不甘心，咬牙再战一年高考。',
    consequence: '用一年青春换一个翻盘的机会：成了逆袭，败了双倍打击。',
  },
  {
    id: 'choose_major', emoji: '🧭', name: '纠结选专业', track: 'career',
    ageStart: 18, ageEnd: 20, delayYears: 4, worthy: true,
    cost: { moodDelta: -3 },
    gain: { identityDelta: 4, wealthMul: 1.1, moodDelta: 2 },
    desc: '在兴趣、钱景与父母意愿之间反复横跳。',
    consequence: '一个志愿定半生：选对了如鱼得水，选错了四年想转行。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 大学生活（18–23 岁）：自由、社团、第一份简历
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'student_council', emoji: '🏛️', name: '学生会主席', track: 'career',
    ageStart: 18, ageEnd: 23, delayYears: 3, worthy: true,
    cost: { moodDelta: -4, eduDelta: -2 },
    gain: { identityDelta: 10, moodDelta: 4 },
    desc: '竞选上位，统筹大型活动与各路人马。',
    consequence: '校园政治初体验：组织力与人脉拉满，也练就了一身打太极的本事。',
  },
  {
    id: 'club_activity', emoji: '🎭', name: '社团达人', track: 'love',
    ageStart: 18, ageEnd: 23, delayYears: 2, worthy: false,
    cost: { eduDelta: -3, moodDelta: -1 },
    gain: { moodDelta: 8, identityDelta: 3 },
    desc: '吉他社、动漫社、辩论队全都掺一脚。',
    consequence: '大学最快乐的回忆来源：朋友一堆、技能点杂，就是 GPA 有点对不起。',
  },
  {
    id: 'scholarship', emoji: '🏆', name: '拿奖学金', track: 'career',
    ageStart: 18, ageEnd: 23, delayYears: 2, worthy: true,
    cost: { moodDelta: -5 },
    gain: { eduDelta: 8, identityDelta: 6, wealthMul: 1.1, moodDelta: 5 },
    desc: 'GPA 卷到年级前列，国奖国励拿到手软。',
    consequence: '学霸光环加身：保研加分、简历闪光，图书馆闭馆音乐听了三年。',
  },
  {
    id: 'fail_course', emoji: '📕', name: '挂科补考', track: 'career',
    ageStart: 18, ageEnd: 23, delayYears: 1, worthy: false, trash: true,
    cost: { eduDelta: -8, identityDelta: -3, moodDelta: -4 },
    gain: { moodDelta: 4 },
    desc: '高数大物轮番挂，重修教室常驻。',
    consequence: '差点延毕：清考惊险过关，绩点被拉花，奖学金和保研彻底无缘。',
  },
  {
    id: 'campus_love', emoji: '🌷', name: '校园恋爱', track: 'love',
    ageStart: 18, ageEnd: 23, delayYears: 0, worthy: false,
    cost: { wealthMul: 0.92, moodDelta: -2 },
    gain: { moodDelta: 12 },
    unlocks: ['graduation_breakup'],
    desc: '食堂一起吃饭，操场一起散步的纯爱。',
    consequence: '最干净的一段感情：没有房车彩礼的算计，只有图书馆并肩自习的心动。',
  },
  {
    id: 'graduation_breakup', emoji: '🍂', name: '毕业分手', track: 'love',
    ageStart: 21, ageEnd: 24, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -10 },
    gain: { identityDelta: 2, moodDelta: 3 },
    requires: ['campus_love'],
    desc: '一个考研一个工作，败给了现实与距离。',
    consequence: '"我们终究还是输给了毕业"：散伙饭吃成了散场，青春就此翻篇。',
  },
  {
    id: 'cet6', emoji: '🔤', name: '考过六级', track: 'career',
    ageStart: 18, ageEnd: 24, delayYears: 1, worthy: true,
    cost: { moodDelta: -3 },
    gain: { eduDelta: 5, identityDelta: 2, moodDelta: 2 },
    desc: '背单词刷真题，啃下英语六级证书。',
    consequence: '求职敲门砖到手：简历多一行，外企和考研都用得上。',
  },
  {
    id: 'internship', emoji: '💼', name: '名企实习', track: 'career',
    ageStart: 19, ageEnd: 24, delayYears: 1, worthy: true,
    cost: { moodDelta: -3, eduDelta: -2 },
    gain: { identityDelta: 6, wealthMul: 1.2, moodDelta: 3 },
    unlocks: ['return_offer'],
    desc: '挤进大厂 / 名企实习，提前体验社畜生活。',
    consequence: '简历含金量飙升：见了世面攒了经验，也提前尝到通勤与加班的苦。',
  },
  {
    id: 'return_offer', emoji: '📜', name: '拿到返聘 offer', track: 'career',
    ageStart: 21, ageEnd: 24, delayYears: 1, worthy: true,
    cost: {},
    gain: { wealthMul: 1.3, identityDelta: 6, moodDelta: 6 },
    requires: ['internship'],
    desc: '实习表现亮眼，毕业直接转正入职。',
    consequence: '别人秋招挤破头，你已锁定 offer：从容毕业，起薪还不低。',
  },
  {
    id: 'college_startup', emoji: '💡', name: '大学创业', track: 'career',
    ageStart: 19, ageEnd: 24, delayYears: 3, worthy: false,
    cost: { wealthMul: 0.7, eduDelta: -4, moodDelta: -4 },
    gain: { wealthMul: 1.6, identityDelta: 6, moodDelta: 5 },
    desc: '拉上室友做项目，参加创业大赛拿融资。',
    consequence: '年少轻狂搞事业：多半是交学费练手，少数人就此起飞。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 考研深造（21–30 岁）：二战、保研、读博的岔路
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'kaoyan_grind', emoji: '📚', name: '备战考研', track: 'career',
    ageStart: 21, ageEnd: 26, delayYears: 2, worthy: true,
    cost: { moodDelta: -10, bodyDelta: -4, wealthMul: 0.95 },
    gain: { eduDelta: 10, identityDelta: 4, moodDelta: 3 },
    unlocks: ['kaoyan_win', 'kaoyan_fail'],
    desc: '自习室占座、政治英语专业课连轴转。',
    consequence: '二战独木桥：一群人陪你卷，最后上岸的就那几个。',
  },
  {
    id: 'kaoyan_win', emoji: '🎓', name: '考研上岸', track: 'career',
    ageStart: 22, ageEnd: 26, delayYears: 3, worthy: true,
    cost: { wealthMul: 0.85, moodDelta: -2 },
    gain: { eduDelta: 12, identityDelta: 10, wealthMul: 1.5, moodDelta: 10 },
    requires: ['kaoyan_grind'],
    unlocks: ['phd'],
    desc: '初试复试双双过线，成功读研。',
    consequence: '上岸的那一刻泪流满面：学历再上一阶，天花板又高了一截。',
  },
  {
    id: 'kaoyan_fail', emoji: '🌧️', name: '考研落榜', track: 'career',
    ageStart: 22, ageEnd: 26, delayYears: 1, worthy: false, event: true,
    cost: { identityDelta: -4, moodDelta: -10 },
    gain: { moodDelta: 2 },
    requires: ['kaoyan_grind'],
    unlocks: ['kaoyan_again', 'reluctant_job'],
    desc: '差几分没过线，调剂也没成。',
    consequence: '一年苦读打了水漂：二战还是工作？同龄人已在职场起跑。',
  },
  {
    id: 'kaoyan_again', emoji: '🔂', name: '二战考研', track: 'career',
    ageStart: 23, ageEnd: 27, delayYears: 2, worthy: false,
    cost: { wealthMul: 0.85, moodDelta: -12, bodyDelta: -3 },
    gain: { eduDelta: 10, identityDelta: 6, moodDelta: 6 },
    requires: ['kaoyan_fail'],
    desc: '不服输，租房脱产再考一年。',
    consequence: '孤注一掷的二战：赌赢了扬眉吐气，赌输了身心俱疲还慢人两步。',
  },
  {
    id: 'reluctant_job', emoji: '😶', name: '将就就业', track: 'career',
    ageStart: 22, ageEnd: 28, delayYears: 1, worthy: false,
    cost: { moodDelta: -5 },
    gain: { wealthMul: 1.1, identityDelta: 2, moodDelta: 2 },
    requires: ['kaoyan_fail'],
    desc: '考研失利后，匆忙找了份糊口的工作。',
    consequence: '先上车再说：起点不高，心里那点不甘要靠日后跳槽来补。',
  },
  {
    id: 'phd', emoji: '🔭', name: '硕博连读', track: 'career',
    ageStart: 24, ageEnd: 30, delayYears: 5, worthy: true,
    cost: { wealthMul: 0.7, bodyDelta: -4, moodDelta: -10 },
    gain: { eduDelta: 16, identityDelta: 14, wealthMul: 1.6, moodDelta: 6 },
    requires: ['kaoyan_win'],
    desc: '一路读到博士，向学术金字塔尖冲刺。',
    consequence: '延毕、秃头、论文血泪：戴上博士帽那天，半生青春已献给实验室。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 求职面试（21–50 岁）：投简历、面试、谈薪、就业方向
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'prep_interview', emoji: '🧑‍💻', name: '突击面试', track: 'career',
    ageStart: 21, ageEnd: 45, delayYears: 1, worthy: true,
    cost: { moodDelta: -4 },
    gain: { identityDelta: 4, wealthMul: 1.15, moodDelta: 2 },
    unlocks: ['big_tech_offer', 'interview_fail'],
    desc: '刷算法、背八股、模拟面，临阵磨枪。',
    consequence: '面试如考试：准备充分则对答如流，临场翻车则当场社死。',
  },
  {
    id: 'big_tech_offer', emoji: '🏢', name: '斩获大厂 offer', track: 'career',
    ageStart: 22, ageEnd: 45, delayYears: 1, worthy: true,
    cost: { moodDelta: -2 },
    gain: { wealthMul: 1.6, identityDelta: 10, moodDelta: 8 },
    requires: ['prep_interview'],
    desc: '过五关斩六将，拿下心仪大厂 offer。',
    consequence: '起薪直接对标行业天花板：朋友圈一片羡慕，也正式踏入 996 围城。',
  },
  {
    id: 'interview_fail', emoji: '📭', name: '海投被拒', track: 'career',
    ageStart: 22, ageEnd: 45, delayYears: 0, worthy: false, event: true,
    cost: { identityDelta: -4, moodDelta: -8 },
    gain: { moodDelta: 2 },
    requires: ['prep_interview'],
    desc: '简历投了两百份，已读不回或感谢信。',
    consequence: '求职寒冬的毒打：自我怀疑拉满，offer 却迟迟不来。',
  },
  {
    id: 'negotiate_salary', emoji: '🤝', name: '谈薪博弈', track: 'career',
    ageStart: 22, ageEnd: 50, delayYears: 0, worthy: true,
    cost: { moodDelta: -2 },
    gain: { wealthMul: 1.2, identityDelta: 2 },
    desc: '拿着竞品 offer，从容向 HR 开价。',
    consequence: '会哭的孩子有奶吃：敢开口多挣两成，闷头接受就是给公司省钱。',
  },
  {
    id: 'state_owned', emoji: '🏦', name: '进国企央企', track: 'career',
    ageStart: 22, ageEnd: 32, delayYears: 2, worthy: true,
    cost: { moodDelta: -4 },
    gain: { identityDelta: 10, wealthMul: 1.1, moodDelta: 5 },
    desc: '考进国企 / 央企，端上半个铁饭碗。',
    consequence: '稳定体面福利好：升迁论资排辈，激情被流程慢慢磨平。',
  },
  {
    id: 'teacher_job', emoji: '🍎', name: '考编当老师', track: 'career',
    ageStart: 22, ageEnd: 35, delayYears: 2, worthy: true,
    cost: { moodDelta: -5 },
    gain: { identityDelta: 8, wealthMul: 1.05, bodyDelta: 1, moodDelta: 6 },
    desc: '考下教师编制，三尺讲台育桃李。',
    consequence: '寒暑假真香：受人尊敬、作息规律，工资不高但胜在安稳长久。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 婚恋相亲（24–40 岁）：脱单、彩礼、催婚、闪婚闪离
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'matchmaking_app', emoji: '📱', name: '软件相亲', track: 'love',
    ageStart: 22, ageEnd: 40, delayYears: 0, worthy: false,
    cost: { wealthMul: 0.97, moodDelta: -3 },
    gain: { moodDelta: 5 },
    desc: '下载交友软件，左滑右滑寻找有缘人。',
    consequence: '线上海选：见光死、照骗、酒托轮番登场，偶尔也能捞到真爱。',
  },
  {
    id: 'parent_nag_marriage', emoji: '📢', name: '被催婚', track: 'love',
    ageStart: 26, ageEnd: 38, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -7 },
    gain: { moodDelta: 1 },
    desc: '每逢佳节被七大姑八大姨花式逼婚。',
    consequence: '相亲安排塞满假期：父母的焦虑变成你的 KPI，过年都不敢回家。',
  },
  {
    id: 'bride_price', emoji: '💰', name: '天价彩礼', track: 'love',
    ageStart: 25, ageEnd: 40, delayYears: 0, worthy: false, event: true,
    cost: { wealthMul: 0.5, moodDelta: -6 },
    gain: { moodDelta: 4, identityDelta: 2 },
    requires: ['blind_date'],
    desc: '为娶 / 嫁对方，掏出几十万彩礼嫁妆。',
    consequence: '甜蜜的负担：六个钱包再次被掏空，婚还没结就先返贫。',
  },
  {
    id: 'flash_marriage', emoji: '⚡', name: '闪婚', track: 'love',
    ageStart: 23, ageEnd: 40, delayYears: 1, worthy: false, trash: true,
    cost: { wealthMul: 0.7, moodDelta: -4 },
    gain: { moodDelta: 8 },
    unlocks: ['divorce'],
    desc: '认识三个月就领证，激情盖过理智。',
    consequence: '冲动的代价：婚后才发现三观不合，磨合成了煎熬。',
  },
  {
    id: 'single_choice', emoji: '🕊️', name: '主动单身', track: 'love',
    ageStart: 28, ageEnd: 60, delayYears: 2, worthy: false,
    cost: { identityDelta: -3 },
    gain: { moodDelta: 7, wealthMul: 1.05 },
    desc: '看透婚姻本质，选择一个人精彩地活。',
    consequence: '一人吃饱全家不饿：自由与存款双在线，偶尔深夜也会有点孤独。',
  },
  {
    id: 'in_law_conflict', emoji: '👵', name: '婆媳大战', track: 'love',
    ageStart: 27, ageEnd: 55, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -8, identityDelta: -2 },
    gain: { moodDelta: 1 },
    requires: ['marriage'],
    desc: '婚后卷入剪不断理还乱的家庭关系。',
    consequence: '夹心饼干的滋味：一边是妈一边是爱人，怎么站队都是错。',
  },
  {
    id: 'naked_marriage', emoji: '🏠', name: '裸婚', track: 'love',
    ageStart: 24, ageEnd: 35, delayYears: 2, worthy: true,
    cost: { moodDelta: -5 },
    gain: { moodDelta: 9, identityDelta: 3 },
    desc: '没房没车没钻戒，凭一腔真爱领证。',
    consequence: '为爱搏一把：物质起点低，但两个人白手起家的劲儿格外足。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 生育养娃（26–50 岁）：备孕、教育、亲子、空巢
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'pregnancy_prep', emoji: '🤰', name: '备孕调理', track: 'love',
    ageStart: 25, ageEnd: 42, delayYears: 1, worthy: true,
    cost: { wealthMul: 0.95, moodDelta: -2 },
    gain: { moodDelta: 5, bodyDelta: 2 },
    requires: ['marriage'],
    unlocks: ['have_child'],
    desc: '戒烟戒酒、补叶酸，为迎接新生命做准备。',
    consequence: '生活方式大调整：为了下一代，先把自己的身体管理起来。',
  },
  {
    id: 'kid_tutoring', emoji: '🎒', name: '鸡娃补课', track: 'love',
    ageStart: 32, ageEnd: 50, delayYears: 3, worthy: false,
    cost: { wealthMul: 0.7, moodDelta: -6 },
    gain: { identityDelta: 4, moodDelta: 2 },
    requires: ['have_child'],
    desc: '奥数、英语、钢琴，给娃报满补习班。',
    consequence: '内卷从娃娃抓起：钱包大出血、亲子关系紧张，效果还得看天赋。',
  },
  {
    id: 'kid_school_district', emoji: '🏫', name: '抢学区房', track: 'love',
    ageStart: 30, ageEnd: 45, delayYears: 1, worthy: false,
    cost: { wealthMul: 0.5, moodDelta: -8 },
    gain: { identityDelta: 6, moodDelta: 3 },
    requires: ['have_child'],
    desc: '为孩子上名校，咬牙买下老破小学区房。',
    consequence: '一平米十几万的过道也买：掏空积蓄换一张入学券，赌的是阶层不下滑。',
  },
  {
    id: 'accompany_kid', emoji: '🧸', name: '陪伴成长', track: 'love',
    ageStart: 28, ageEnd: 50, delayYears: 2, worthy: true,
    cost: { wealthMul: 0.95, moodDelta: -2 },
    gain: { moodDelta: 12, identityDelta: 2 },
    requires: ['have_child'],
    desc: '少加点班，多陪孩子读绘本、过家家。',
    consequence: '童年只有一次：错过的会议能再开，孩子的第一次却不会重来。',
  },
  {
    id: 'empty_nest', emoji: '🪹', name: '空巢期', track: 'love',
    ageStart: 48, ageEnd: 65, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -8 },
    gain: { moodDelta: 3, wealthMul: 1.05 },
    requires: ['have_child'],
    desc: '孩子长大离家，房子突然空荡荡。',
    consequence: '完成阶段性使命：失落与轻松并存，得重新学着为自己而活。',
  },
  {
    id: 'kid_rebel', emoji: '🚪', name: '子女叛逆', track: 'love',
    ageStart: 40, ageEnd: 55, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -7, bodyDelta: -1 },
    gain: { identityDelta: 1 },
    requires: ['have_child'],
    desc: '轮到你体验当年自己叛逆时父母的崩溃。',
    consequence: '因果循环：和孩子的每一次争吵，都让你更懂自己的父母。',
  },
  {
    id: 'childfree', emoji: '🚫', name: '丁克家庭', track: 'love',
    ageStart: 28, ageEnd: 45, delayYears: 3, worthy: false,
    cost: { identityDelta: -4 },
    gain: { moodDelta: 7, wealthMul: 1.15 },
    requires: ['marriage'],
    desc: '两人世界，把养娃的钱拿来享受生活。',
    consequence: '潇洒二人转：旅行存款随心所欲，代价是老来无子的非议与孤独。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 健康与疾病（30–80 岁）：作息、慢病、意外、康复
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'stay_up_late', emoji: '🌙', name: '长期熬夜', track: 'career',
    ageStart: 18, ageEnd: 55, delayYears: 3, worthy: false, trash: true,
    cost: { bodyDelta: -10, moodDelta: -2 },
    gain: { moodDelta: 5 },
    desc: '报复性熬夜刷剧打游戏，凌晨三点不睡。',
    consequence: '快乐肥宅水续命：黑眼圈、脱发、内分泌失调组团来访。',
  },
  {
    id: 'quit_smoking', emoji: '🚭', name: '戒烟戒酒', track: 'career',
    ageStart: 30, ageEnd: 70, delayYears: 2, worthy: true,
    cost: { moodDelta: -4 },
    gain: { bodyDelta: 10, moodDelta: 4 },
    desc: '为了健康，下决心戒掉烟酒。',
    consequence: '戒断反应难熬：挺过去肺和肝都松了口气，寿命表往后挪。',
  },
  {
    id: 'chronic_disease', emoji: '💊', name: '慢病缠身', track: 'career',
    ageStart: 40, ageEnd: 75, delayYears: 0, worthy: false, event: true,
    cost: { bodyDelta: -12, moodDelta: -6, wealthMul: 0.9 },
    gain: {},
    desc: '三高 / 糖尿病找上门，从此药不离身。',
    consequence: '中年健康滑铁卢：忌口、吃药、定期复查，生活质量打了折。',
  },
  {
    id: 'serious_illness', emoji: '🏥', name: '大病一场', track: 'career',
    ageStart: 35, ageEnd: 80, delayYears: 0, worthy: false, event: true,
    cost: { bodyDelta: -18, moodDelta: -12, wealthMul: 0.6 },
    gain: { moodDelta: 3, identityDelta: 1 },
    unlocks: ['recover_illness'],
    desc: '一纸诊断书，把人生按下暂停键。',
    consequence: '鬼门关前走一遭：积蓄被医药费吞噬，但也看淡了名利，重排了人生优先级。',
  },
  {
    id: 'recover_illness', emoji: '🌱', name: '康复重生', track: 'career',
    ageStart: 36, ageEnd: 80, delayYears: 1, worthy: true,
    cost: { wealthMul: 0.95 },
    gain: { bodyDelta: 8, moodDelta: 10 },
    requires: ['serious_illness'],
    desc: '挺过治疗，慢慢恢复元气。',
    consequence: '劫后余生格外珍惜：从此早睡早起、好好吃饭，把健康放在第一位。',
  },
  {
    id: 'car_accident', emoji: '🚑', name: '遭遇车祸', track: 'career',
    ageStart: 18, ageEnd: 75, delayYears: 0, worthy: false, event: true,
    cost: { bodyDelta: -14, moodDelta: -8, wealthMul: 0.85 },
    gain: { moodDelta: 2 },
    desc: '一场突如其来的意外，住院数月。',
    consequence: '飞来横祸：身体留下后遗症，对"平安"二字有了切肤的理解。',
  },
  {
    id: 'buy_insurance', emoji: '🛡️', name: '配置保险', track: 'career',
    ageStart: 25, ageEnd: 55, delayYears: 1, worthy: true,
    cost: { wealthMul: 0.93 },
    gain: { moodDelta: 5, identityDelta: 1 },
    desc: '重疾险 + 医疗险 + 意外险，给家庭兜底。',
    consequence: '花小钱买安心：真出事时不至于因病返贫，是成年人的责任感。',
  },
  {
    id: 'marathon', emoji: '🏅', name: '跑马拉松', track: 'career',
    ageStart: 22, ageEnd: 60, delayYears: 2, worthy: true,
    cost: { bodyDelta: -2, moodDelta: -2, wealthMul: 0.98 },
    gain: { bodyDelta: 12, moodDelta: 8, identityDelta: 3 },
    requires: ['fitness'],
    desc: '从五公里跑到全程 42 公里，挑战极限。',
    consequence: '完赛奖牌挂满墙：意志力与心肺功能双双封神，朋友圈打卡圣地。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 财富进阶与暴雷（25–60 岁）：买房、炒股、踩坑、暴富
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'stock_market', emoji: '📉', name: '炒股入市', track: 'career',
    ageStart: 22, ageEnd: 65, delayYears: 1, worthy: false,
    cost: { wealthMul: 0.85, moodDelta: -4 },
    gain: { wealthMul: 1.3, moodDelta: 3 },
    desc: '杀入 A 股，追涨杀跌当韭菜。',
    consequence: '七亏二平一赚：牛市飘飘然，熊市套到怀疑人生，最后多半给市场交学费。',
  },
  {
    id: 'p2p_scam', emoji: '🕳️', name: '理财暴雷', track: 'career',
    ageStart: 25, ageEnd: 60, delayYears: 0, worthy: false, event: true,
    cost: { wealthMul: 0.4, moodDelta: -12 },
    gain: { identityDelta: 1 },
    desc: '高收益理财 / P2P 卷款跑路，血本无归。',
    consequence: '贪小利吃大亏：半生积蓄一夜清零，维权群里又多了一个你。',
  },
  {
    id: 'second_house', emoji: '🏘️', name: '买房收租', track: 'career',
    ageStart: 32, ageEnd: 55, delayYears: 3, worthy: true,
    cost: { wealthMul: 0.55, moodDelta: -3 },
    gain: { wealthMul: 1.5, identityDelta: 6, moodDelta: 4 },
    requires: ['buy_house'],
    desc: '上车第二套房，靠租金睡后收入。',
    consequence: '包租公 / 婆养成：现金流更稳，前提是没买在高位站岗。',
  },
  {
    id: 'lottery_win', emoji: '🎰', name: '中了彩票', track: 'career',
    ageStart: 18, ageEnd: 75, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -1 },
    gain: { wealthMul: 2.0, moodDelta: 14 },
    desc: '两块钱中了大奖，天降横财。',
    consequence: '人生开挂的瞬间：暴富的快乐很真实，能不能守住又是另一回事。',
  },
  {
    id: 'pyramid_scheme', emoji: '🔺', name: '误入传销', track: 'career',
    ageStart: 20, ageEnd: 45, delayYears: 0, worthy: false, event: true,
    cost: { wealthMul: 0.6, moodDelta: -10, identityDelta: -6 },
    gain: { moodDelta: 2 },
    desc: '被"高薪招聘"骗进传销窝点。',
    consequence: '洗脑与控制的噩梦：搭进去钱和人脉，逃出来后看谁都像骗子。',
  },
  {
    id: 'angel_investor', emoji: '😇', name: '天使投资', track: 'career',
    ageStart: 35, ageEnd: 65, delayYears: 5, worthy: true,
    cost: { wealthMul: 0.6, moodDelta: -3 },
    gain: { wealthMul: 2.2, identityDelta: 8, moodDelta: 6 },
    requires: ['startup'],
    desc: '功成名就后，投钱扶持后辈创业。',
    consequence: '投十个中一个就回本：眼光毒辣则财富自由，看走眼则给项目陪葬。',
  },
  {
    id: 'debt_trap', emoji: '💳', name: '负债缠身', track: 'career',
    ageStart: 22, ageEnd: 55, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.5, moodDelta: -10 },
    gain: { moodDelta: 4 },
    desc: '信用卡套现、网贷拆东补西，越滚越大。',
    consequence: '提前消费的反噬：利滚利压得喘不过气，催收电话成了日常 BGM。',
  },
  {
    id: 'financial_freedom', emoji: '🏖️', name: '财务自由', track: 'career',
    ageStart: 40, ageEnd: 70, delayYears: 1, worthy: true,
    cost: {},
    gain: { wealthMul: 1.3, moodDelta: 14, bodyDelta: 3, identityDelta: 6 },
    requires: ['invest'],
    desc: '被动收入覆盖支出，从此上班全凭心情。',
    consequence: '打工人的终极梦想达成：时间彻底属于自己，焦虑这才真正退场。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 职场政治与转折（28–55 岁）：站队、背锅、裸辞、转行
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'office_politics', emoji: '🎯', name: '站队博弈', track: 'career',
    ageStart: 28, ageEnd: 52, delayYears: 2, worthy: false,
    cost: { moodDelta: -6 },
    gain: { identityDelta: 8, wealthMul: 1.3, moodDelta: 1 },
    desc: '在派系斗争里押宝，赌一个晋升通道。',
    consequence: '职场厚黑学：站对了平步青云，站错了被一锅端，全凭眼力与运气。',
  },
  {
    id: 'take_blame', emoji: '🪤', name: '替人背锅', track: 'career',
    ageStart: 25, ageEnd: 50, delayYears: 0, worthy: false, event: true,
    cost: { identityDelta: -8, moodDelta: -8 },
    gain: { moodDelta: 1 },
    desc: '项目暴雷，被领导推出去当替罪羊。',
    consequence: '职场最憋屈时刻：锅是你的，功是别人的，敢怒不敢言。',
  },
  {
    id: 'laid_off', emoji: '📦', name: '中年被裁', track: 'career',
    ageStart: 35, ageEnd: 55, delayYears: 0, worthy: false, event: true,
    cost: { wealthMul: 0.8, identityDelta: -8, moodDelta: -12 },
    gain: { moodDelta: 2 },
    unlocks: ['career_switch', 'gig_economy'],
    desc: '一纸优化通知，35 岁危机成了现实。',
    consequence: '抱着纸箱走出大厦：上有老下有小、房贷车贷压顶，简历却已不再吃香。',
  },
  {
    id: 'career_switch', emoji: '🔀', name: '半路转行', track: 'career',
    ageStart: 28, ageEnd: 50, delayYears: 3, worthy: true,
    cost: { wealthMul: 0.8, identityDelta: -4, moodDelta: -6 },
    gain: { wealthMul: 1.4, identityDelta: 6, moodDelta: 6 },
    desc: '跳出舒适区，转去一个全新的行业重头学。',
    consequence: '从零开始的勇气：阵痛期收入腰斩，熬过去则打开第二人生。',
  },
  {
    id: 'gig_economy', emoji: '🛵', name: '送外卖跑滴滴', track: 'career',
    ageStart: 22, ageEnd: 55, delayYears: 0, worthy: false,
    cost: { bodyDelta: -6, identityDelta: -3 },
    gain: { wealthMul: 1.1, moodDelta: 2 },
    desc: '放下身段，靠体力赚一份踏实的收入。',
    consequence: '风里雨里讨生活：多劳多得没有天花板，也没有五险一金的兜底。',
  },
  {
    id: 'go_abroad_work', emoji: '🌐', name: '出海打工', track: 'career',
    ageStart: 24, ageEnd: 45, delayYears: 3, worthy: true,
    cost: { wealthMul: 0.85, moodDelta: -6 },
    gain: { wealthMul: 1.6, identityDelta: 8, moodDelta: 4 },
    desc: '远赴海外工作，赚一份免税的高薪。',
    consequence: '异国他乡搏前程：收入翻倍、视野大开，孤独与文化冲击如影随形。',
  },
  {
    id: 'become_freelancer', emoji: '🦅', name: '自由职业', track: 'career',
    ageStart: 26, ageEnd: 55, delayYears: 2, worthy: false,
    cost: { wealthMul: 0.85, moodDelta: -4 },
    gain: { wealthMul: 1.2, moodDelta: 9 },
    desc: '辞职单干，做设计 / 写作 / 自媒体接单。',
    consequence: '自由的另一面是不稳定：没人管你，也没人给你发底薪和社保。',
  },
  {
    id: 'wechat_business', emoji: '🛍️', name: '微商带货', track: 'career',
    ageStart: 24, ageEnd: 50, delayYears: 1, worthy: false, trash: true,
    cost: { wealthMul: 0.8, identityDelta: -5, moodDelta: -2 },
    gain: { wealthMul: 1.1, moodDelta: 4 },
    desc: '朋友圈刷屏卖面膜，发展下线代理。',
    consequence: '杀熟生意难长久：囤了一仓库货，亲戚朋友被屏蔽了大半。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 中年危机与觉醒（38–55 岁）：油腻、出轨、重塑、断舍离
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'midlife_crisis', emoji: '🫩', name: '中年危机', track: 'love',
    ageStart: 38, ageEnd: 52, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -10, bodyDelta: -3 },
    gain: { identityDelta: 1 },
    unlocks: ['midlife_reinvent'],
    desc: '事业到顶、激情消退，开始怀疑人生意义。',
    consequence: '上不去也下不来：一边是房贷家庭，一边是无处安放的中年迷茫。',
  },
  {
    id: 'midlife_reinvent', emoji: '🔥', name: '重塑自我', track: 'love',
    ageStart: 40, ageEnd: 58, delayYears: 2, worthy: true,
    cost: { wealthMul: 0.95, moodDelta: -3 },
    gain: { moodDelta: 11, bodyDelta: 5, identityDelta: 4 },
    requires: ['midlife_crisis'],
    desc: '健身、学习、捡回旧梦，给人生第二春。',
    consequence: '四十不惑的另一种解法：与其内耗，不如把自己重新活一遍。',
  },
  {
    id: 'declutter', emoji: '🧹', name: '断舍离', track: 'love',
    ageStart: 35, ageEnd: 70, delayYears: 1, worthy: true,
    cost: {},
    gain: { moodDelta: 7 },
    desc: '清空冗余物品与无效社交，给生活做减法。',
    consequence: '物质极简、精神极富：扔掉的是杂物，腾出的是心里的空间。',
  },
  {
    id: 'caregiver', emoji: '🧑‍🦽', name: '照顾老人', track: 'love',
    ageStart: 40, ageEnd: 65, delayYears: 0, worthy: true, event: true,
    cost: { wealthMul: 0.9, bodyDelta: -4, moodDelta: -8 },
    gain: { identityDelta: 4, moodDelta: 3 },
    desc: '父母年迈卧病，你成了家里的顶梁柱。',
    consequence: '久病床前的考验：身心俱疲，却也是为人子女最后的尽孝时光。',
  },
  {
    id: 'reunion_show_off', emoji: '🎟️', name: '同学会攀比', track: 'love',
    ageStart: 30, ageEnd: 55, delayYears: 0, worthy: false,
    cost: { wealthMul: 0.97, moodDelta: -4 },
    gain: { moodDelta: 4, identityDelta: 2 },
    desc: '多年后重聚，席间暗暗较量混得如何。',
    consequence: '当年的差生开了公司，学霸还在打工：人生的剧本总爱开玩笑。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 兴趣与精神生活（任意年龄）：旅行、信仰、创作、第二技能
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'learn_language', emoji: '🗣️', name: '自学外语', track: 'career',
    ageStart: 16, ageEnd: 60, delayYears: 2, worthy: true,
    cost: { moodDelta: -2 },
    gain: { eduDelta: 6, identityDelta: 3, moodDelta: 3 },
    desc: '利用业余时间啃下一门新语言。',
    consequence: '多一门语言多一个世界：旅行、追剧、求职都解锁了新副本。',
  },
  {
    id: 'write_novel', emoji: '✒️', name: '写小说', track: 'career',
    ageStart: 16, ageEnd: 70, delayYears: 3, worthy: false,
    cost: { moodDelta: -3 },
    gain: { moodDelta: 8, identityDelta: 4, wealthMul: 1.05 },
    desc: '在键盘上构建一个属于自己的世界。',
    consequence: '深夜码字的孤独与狂喜：多数太监烂尾，偶有签约爆款逆袭。',
  },
  {
    id: 'become_influencer', emoji: '📹', name: '做up主网红', track: 'career',
    ageStart: 16, ageEnd: 50, delayYears: 2, worthy: false,
    cost: { wealthMul: 0.9, moodDelta: -4 },
    gain: { wealthMul: 1.5, identityDelta: 8, moodDelta: 6 },
    desc: '拍视频做直播，押注流量经济。',
    consequence: '台前光鲜台后肝：火了名利双收，糊了一地设备吃灰。',
  },
  {
    id: 'mountain_hiking', emoji: '🏔️', name: '徒步登山', track: 'love',
    ageStart: 18, ageEnd: 60, delayYears: 1, worthy: true,
    cost: { bodyDelta: -1, wealthMul: 0.98 },
    gain: { bodyDelta: 6, moodDelta: 9 },
    desc: '背上行囊，把脚印留在山川湖海。',
    consequence: '在自然里充电：体能与心境双修，手机信号差反而睡得香。',
  },
  {
    id: 'meditation', emoji: '🧘', name: '冥想修行', track: 'love',
    ageStart: 22, ageEnd: 80, delayYears: 1, worthy: true,
    cost: {},
    gain: { moodDelta: 8, bodyDelta: 2 },
    desc: '正念冥想 / 打坐，与自己的内心和解。',
    consequence: '向内求的力量：焦虑减半、专注翻倍，情绪有了缓冲垫。',
  },
  {
    id: 'gambling_addiction', emoji: '🎲', name: '沉迷赌博', track: 'love',
    ageStart: 22, ageEnd: 60, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.3, moodDelta: -8, identityDelta: -8 },
    gain: { moodDelta: 7 },
    desc: '赌场 / 网赌越陷越深，幻想翻本暴富。',
    consequence: '十赌九输的深渊：房子车子老婆孩子，最后可能一样不剩。',
  },
  {
    id: 'religion_faith', emoji: '🕯️', name: '皈依信仰', track: 'love',
    ageStart: 25, ageEnd: 85, delayYears: 1, worthy: false,
    cost: { wealthMul: 0.98 },
    gain: { moodDelta: 7, identityDelta: 1 },
    desc: '在信仰里寻找心灵的归宿与慰藉。',
    consequence: '精神有了寄托：面对无常多了一份从容，也多了一份敬畏。',
  },
  {
    id: 'collect_hobby', emoji: '🏺', name: '收藏发烧', track: 'love',
    ageStart: 30, ageEnd: 75, delayYears: 2, worthy: false,
    cost: { wealthMul: 0.85, moodDelta: -1 },
    gain: { moodDelta: 8, identityDelta: 2 },
    desc: '手办 / 球鞋 / 古玩 / 黑胶，越买越上头。',
    consequence: '爱好烧钱无底洞：精神富足感拉满，钱包和老婆的脸色一起变绿。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 晚年与谢幕（60–100 岁）：退休、含饴弄孙、回望
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'retire_well', emoji: '🌅', name: '体面退休', track: 'career',
    ageStart: 55, ageEnd: 70, delayYears: 1, worthy: true,
    cost: {},
    gain: { moodDelta: 10, bodyDelta: 2, identityDelta: 2 },
    desc: '攒够养老金，从职场光荣退场。',
    consequence: '终于卸下重担：钓鱼下棋养花种菜，把前半生欠自己的悠闲补回来。',
  },
  {
    id: 'square_dance', emoji: '💃', name: '广场舞天团', track: 'love',
    ageStart: 55, ageEnd: 85, delayYears: 1, worthy: false,
    cost: {},
    gain: { bodyDelta: 5, moodDelta: 8, identityDelta: 2 },
    desc: '加入广场舞天团，C 位领舞气场全开。',
    consequence: '退休生活的快乐源泉：身体活络、社交满满，音响一响精神百倍。',
  },
  {
    id: 'grandchild', emoji: '👶', name: '含饴弄孙', track: 'love',
    ageStart: 55, ageEnd: 85, delayYears: 0, worthy: true,
    cost: { bodyDelta: -3, wealthMul: 0.97 },
    gain: { moodDelta: 12 },
    requires: ['have_child'],
    desc: '帮忙带孙辈，重温为人父母的甜蜜。',
    consequence: '隔代亲上头：被孙子孙女的奶音治愈，腰酸背痛也心甘情愿。',
  },
  {
    id: 'travel_world_old', emoji: '🧳', name: '环游世界', track: 'love',
    ageStart: 55, ageEnd: 80, delayYears: 0, worthy: false,
    cost: { wealthMul: 0.8, bodyDelta: -2 },
    gain: { moodDelta: 13, identityDelta: 2 },
    desc: '退休后了却心愿，带着老伴看遍山河。',
    consequence: '把年轻时没时间去的地方都补上：钱花得值，回忆塞满了相册。',
  },
  {
    id: 'write_memoir', emoji: '📔', name: '撰写回忆录', track: 'love',
    ageStart: 60, ageEnd: 95, delayYears: 1, worthy: true,
    cost: {},
    gain: { moodDelta: 9, identityDelta: 3 },
    desc: '把跌宕一生写成文字，留给后人。',
    consequence: '与往事和解：荣辱得失落于纸上，这一生总算有了个交代。',
  },
  {
    id: 'lonely_elder', emoji: '🪑', name: '孤独终老', track: 'love',
    ageStart: 60, ageEnd: 95, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -10, bodyDelta: -2 },
    gain: {},
    desc: '子女远走、老伴先行，独自面对漫长晚景。',
    consequence: '空房子里的钟摆声格外响：年轻时的选择，到这一刻都成了回响。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 童年杂记（4–12 岁）：小日常、小意外、小确幸
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'lost_tooth', emoji: '🦷', name: '换牙啦', track: 'love',
    ageStart: 5, ageEnd: 9, delayYears: 0, worthy: false,
    cost: {},
    gain: { moodDelta: 4 },
    desc: '门牙摇摇欲坠，咬苹果时"啪"地掉了。',
    consequence: '漏风的笑容很可爱：把牙塞枕头下，等牙仙换来一颗糖。',
  },
  {
    id: 'summer_homework', emoji: '📓', name: '暑假作业', track: 'career',
    ageStart: 7, ageEnd: 14, delayYears: 1, worthy: false,
    cost: { moodDelta: -3 },
    gain: { eduDelta: 3, moodDelta: 2 },
    desc: '开学前一晚疯狂赶两个月的作业。',
    consequence: '熬夜补天的童年噩梦：字迹潦草、答案靠抄，从此痛恨拖延。',
  },
  {
    id: 'catch_cicada', emoji: '🦗', name: '上树掏鸟窝', track: 'love',
    ageStart: 6, ageEnd: 12, delayYears: 0, worthy: false, trash: true,
    cost: { bodyDelta: -2 },
    gain: { moodDelta: 6 },
    desc: '爬树捉知了、下河摸鱼的野孩子日常。',
    consequence: '撒野的快乐无可替代：偶尔摔得鼻青脸肿，回家还得挨顿揍。',
  },
  {
    id: 'first_pocket_money', emoji: '🪙', name: '攒零花钱', track: 'career',
    ageStart: 7, ageEnd: 14, delayYears: 3, worthy: true,
    cost: { moodDelta: -1 },
    gain: { moodDelta: 4, wealthMul: 1.02 },
    desc: '把压岁钱和零花钱存进储蓄罐。',
    consequence: '财商启蒙第一课：延迟满足的甜头，从小猪存钱罐里咂摸出来。',
  },
  {
    id: 'school_performance', emoji: '🎤', name: '六一演出', track: 'love',
    ageStart: 6, ageEnd: 12, delayYears: 0, worthy: false,
    cost: { moodDelta: -1 },
    gain: { moodDelta: 6, identityDelta: 2 },
    desc: '儿童节登台表演，紧张得手心冒汗。',
    consequence: '聚光灯下的高光时刻：台下父母举着相机，笑得比谁都灿烂。',
  },
  {
    id: 'pet_died_child', emoji: '🐰', name: '宠物离世', track: 'love',
    ageStart: 6, ageEnd: 16, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -7 },
    gain: { identityDelta: 1 },
    desc: '养了多年的小动物离开，第一次直面死亡。',
    consequence: '人生第一课叫离别：哭红了眼，也第一次懂得了珍惜与无常。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 青春纪事（13–19 岁）：社交、形象、第一次
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'acne_struggle', emoji: '😣', name: '战痘青春', track: 'love',
    ageStart: 13, ageEnd: 20, delayYears: 1, worthy: false,
    cost: { moodDelta: -4 },
    gain: { moodDelta: 3 },
    desc: '满脸青春痘，对着镜子各种纠结。',
    consequence: '容貌焦虑初体验：试遍各种护肤偏方，长大后才与皮肤和解。',
  },
  {
    id: 'best_friend_teen', emoji: '🫂', name: '死党闺蜜', track: 'love',
    ageStart: 12, ageEnd: 20, delayYears: 2, worthy: true,
    cost: {},
    gain: { moodDelta: 9, identityDelta: 2 },
    desc: '有了无话不谈、形影不离的好朋友。',
    consequence: '青春期最坚固的同盟：一起逃课、一起追星、一起哭过笑过。',
  },
  {
    id: 'graduation_trip', emoji: '🚌', name: '毕业旅行', track: 'love',
    ageStart: 15, ageEnd: 23, delayYears: 0, worthy: false,
    cost: { wealthMul: 0.96, moodDelta: -1 },
    gain: { moodDelta: 9 },
    desc: '和同学来一场说走就走的散伙旅行。',
    consequence: '青春的句号画得很圆：照片洗了一沓，誓言"常联系"多半没做到。',
  },
  {
    id: 'part_time_teen', emoji: '🧋', name: '假期打工', track: 'career',
    ageStart: 15, ageEnd: 22, delayYears: 2, worthy: true,
    cost: { bodyDelta: -2, moodDelta: -2 },
    gain: { wealthMul: 1.05, identityDelta: 3, moodDelta: 3 },
    desc: '奶茶店 / 服务员 / 发传单，赚第一桶金。',
    consequence: '挣钱不易的第一课：脚站酸了、被客人刁难过，工资到手却格外香。',
  },
  {
    id: 'fan_chasing', emoji: '🌟', name: '疯狂追星', track: 'love',
    ageStart: 12, ageEnd: 25, delayYears: 0, worthy: false, trash: true,
    cost: { wealthMul: 0.9, eduDelta: -3, moodDelta: -1 },
    gain: { moodDelta: 8 },
    desc: '为爱豆打榜、应援、买专辑，氪金又氪命。',
    consequence: '青春的热血有处安放：精神快乐拉满，钱包和成绩一起阵亡。',
  },
  {
    id: 'driving_license', emoji: '🚙', name: '考驾照', track: 'career',
    ageStart: 18, ageEnd: 40, delayYears: 0, worthy: true,
    cost: { wealthMul: 0.96, moodDelta: -3 },
    gain: { moodDelta: 4, identityDelta: 1 },
    desc: '科目一到科目四，闯关式拿下驾照。',
    consequence: '被教练吼到怀疑人生：本子到手那刻，仿佛多了一项生存技能。',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 扩充事件库 · 青年日常（22–35 岁）：租房、社交、消费、成长
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'rent_alone', emoji: '🔑', name: '独自租房', track: 'love',
    ageStart: 21, ageEnd: 40, delayYears: 1, worthy: true,
    cost: { wealthMul: 0.9, moodDelta: -3 },
    gain: { moodDelta: 6, identityDelta: 2 },
    desc: '搬出合租，拥有第一个完全属于自己的家。',
    consequence: '一个人的自由与孤独：深夜加班回到空屋，也终于不用看人脸色。',
  },
  {
    id: 'flatmate_drama', emoji: '🚪', name: '合租闹剧', track: 'love',
    ageStart: 20, ageEnd: 32, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -5 },
    gain: { moodDelta: 2 },
    desc: '和室友因卫生、噪音、费用闹得不可开交。',
    consequence: '共享空间的修罗场：见识了各种奇葩，也学会了边界与忍让。',
  },
  {
    id: 'consumer_loan', emoji: '🛒', name: '超前消费', track: 'career',
    ageStart: 20, ageEnd: 40, delayYears: 1, worthy: false, trash: true,
    cost: { wealthMul: 0.8, moodDelta: -2 },
    gain: { moodDelta: 6 },
    desc: '花呗信用卡分期，把想要的统统买回家。',
    consequence: '精致穷的真实写照：朋友圈光鲜亮丽，月底吃土还款。',
  },
  {
    id: 'save_money_plan', emoji: '🏦', name: '强制储蓄', track: 'career',
    ageStart: 22, ageEnd: 50, delayYears: 3, worthy: true,
    cost: { moodDelta: -2 },
    gain: { wealthMul: 1.2, moodDelta: 3 },
    desc: '每月工资先存后花，强制攒下应急金。',
    consequence: '反脆弱的底气：账户数字慢慢变厚，面对意外时不再慌张。',
  },
  {
    id: 'social_anxiety', emoji: '😶‍🌫️', name: '社恐内耗', track: 'love',
    ageStart: 18, ageEnd: 45, delayYears: 2, worthy: false,
    cost: { identityDelta: -4, moodDelta: -6 },
    gain: { moodDelta: 2 },
    unlocks: ['see_counselor'],
    desc: '害怕社交、回避人群，独处才有安全感。',
    consequence: '人群中的隐形人：错过了一些机会，也守住了一方清净。',
  },
  {
    id: 'networking', emoji: '🤝', name: '混圈拓人脉', track: 'career',
    ageStart: 24, ageEnd: 50, delayYears: 2, worthy: true,
    cost: { wealthMul: 0.95, moodDelta: -3 },
    gain: { identityDelta: 6, wealthMul: 1.2, moodDelta: 2 },
    desc: '参加行业局、商会饭局，广结善缘。',
    consequence: '人脉即钱脉：递出去的名片有去无回居多，偶尔一个贵人改变命运。',
  },
  {
    id: 'learn_coding', emoji: '⌨️', name: '转码自学', track: 'career',
    ageStart: 20, ageEnd: 40, delayYears: 2, worthy: true,
    cost: { moodDelta: -5, bodyDelta: -2 },
    gain: { wealthMul: 1.4, identityDelta: 5, moodDelta: 3 },
    desc: '啃文档刷题报培训班，转行进 IT。',
    consequence: '从零到能写代码：头发掉了一把，工资也翻了一倍。',
  },
  {
    id: 'get_certified', emoji: '🏷️', name: '考证充电', track: 'career',
    ageStart: 22, ageEnd: 55, delayYears: 1, worthy: true,
    cost: { wealthMul: 0.96, moodDelta: -3 },
    gain: { identityDelta: 4, wealthMul: 1.15, moodDelta: 2 },
    desc: 'CPA / 法考 / PMP，含金量证书傍身。',
    consequence: '一证在手底气足：备考的夜晚很苦，加薪跳槽时很甜。',
  },
  {
    id: 'move_to_bigcity', emoji: '🌆', name: '北漂沪漂', track: 'career',
    ageStart: 21, ageEnd: 38, delayYears: 3, worthy: true,
    cost: { wealthMul: 0.85, moodDelta: -6, bodyDelta: -2 },
    gain: { wealthMul: 1.5, identityDelta: 6, moodDelta: 4 },
    unlocks: ['return_hometown'],
    desc: '揣着梦想挤进一线城市闯荡。',
    consequence: '机会与压力并存：群租地铁加班是常态，但平台与眼界确实不一样。',
  },
  {
    id: 'return_hometown', emoji: '🏡', name: '逃离北上广', track: 'career',
    ageStart: 28, ageEnd: 45, delayYears: 2, worthy: false,
    cost: { wealthMul: 0.85, identityDelta: -3 },
    gain: { moodDelta: 9, bodyDelta: 3 },
    requires: ['move_to_bigcity'],
    desc: '厌倦漂泊，回老家求一份安稳与团圆。',
    consequence: '逃离内卷回到小城：节奏慢了、离家近了，野心也慢慢被磨平。',
  },
  {
    id: 'estranged_friend', emoji: '🥶', name: '友尽绝交', track: 'love',
    ageStart: 18, ageEnd: 60, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -6 },
    gain: { identityDelta: 1, moodDelta: 2 },
    desc: '曾经的好友因借钱 / 误会渐行渐远。',
    consequence: '成年人的友谊说断就断：有些人只能陪你走一段，散场不必强留。',
  },
  {
    id: 'social_media_addiction', emoji: '📲', name: '刷手机成瘾', track: 'love',
    ageStart: 14, ageEnd: 70, delayYears: 2, worthy: false, trash: true,
    cost: { bodyDelta: -4, eduDelta: -2, moodDelta: -2 },
    gain: { moodDelta: 5 },
    desc: '短视频一刷一整天，注意力被切成碎片。',
    consequence: '多巴胺快餐上瘾：时间在指尖溜走，回过神已是深夜。',
  },
  {
    id: 'adopt_child', emoji: '🤱', name: '收养孩子', track: 'love',
    ageStart: 30, ageEnd: 50, delayYears: 2, worthy: true,
    cost: { wealthMul: 0.8, moodDelta: -4 },
    gain: { moodDelta: 12, identityDelta: 5 },
    desc: '给一个没有家的孩子一个温暖的港湾。',
    consequence: '血缘之外的亲情：付出更多耐心与爱，收获同样真挚的"妈妈/爸爸"。',
  },
  {
    id: 'breakup_heartbreak', emoji: '💔', name: '痛苦分手', track: 'love',
    ageStart: 18, ageEnd: 45, delayYears: 0, worthy: false, event: true,
    cost: { moodDelta: -11, bodyDelta: -1 },
    gain: { identityDelta: 2, moodDelta: 3 },
    desc: '一段认真的感情走到尽头，撕心裂肺。',
    consequence: '失恋的夜晚最漫长：循环播放伤感歌，哭过之后人会成长一点。',
  },
  {
    id: 'reconcile_ex', emoji: '🔙', name: '复合旧爱', track: 'love',
    ageStart: 20, ageEnd: 45, delayYears: 1, worthy: false, trash: true,
    cost: { moodDelta: -4 },
    gain: { moodDelta: 7 },
    requires: ['breakup_heartbreak'],
    desc: '抵不住回忆，和前任破镜重圆。',
    consequence: '重蹈覆辙的概率很高：当初分开的原因，往往还在原地等着。',
  },
]

export const CHOICE_BY_ID = new Map(LIFE_CHOICES.map((c) => [c.id, c]))
